export enum PlayerState {
  Stand = 'Stand',
  TurnLeft = 'TurnLeft',
  TurnRight = 'TurnRight',
  TurnUp = 'TurnUp',
  TurnDown = 'TurnDown',
  MoveLeft = 'MoveLeft',
  MoveRight = 'MoveRight',
  MoveUp = 'MoveUp',
  MoveDown = 'MoveDown',
  Fall = 'Fall',
  Trapped = 'Trapped',
  OnStairs = 'OnStairs',
  OnCrossbar = 'OnCrossbar',
  OnCrossbarMoveLeft = 'OnCrossbarMoveLeft',
  OnCrossbarMoveRight = 'OnCrossbarMoveRight',
  Dying = 'Dying',
  GameOver = 'GameOver',
}
