import {
  MAN_MOVING_LEFT_FRAME_1,
  MAN_STANDING_FRAME_1,
  MAN_MOVING_RIGHT_FRAME_1,
  MAN_STANDING_FRAME_2,
  MAN_FALLING_FRAME_1,
  MAN_FALLING_FRAME_3,
  MAN_FALLING_FRAME_2,
  MAN_MOVING_LEFT_FRAME_2,
  MAN_MOVING_LEFT_FRAME_3,
  MAN_MOVING_RIGHT_FRAME_3,
  MAN_MOVING_RIGHT_FRAME_2,
  MAN_CLIMBING_FRAME_1,
  MAN_CLIMBING_FRAME_2,
  MAN_CLIMBING_FRAME_3,
  MAN_ON_STAIRS_FRAME_3,
  MAN_ON_STAIRS_FRAME_2,
  MAN_ON_STAIRS_FRAME_1,
  MAN_ON_CROSSBAR_FRAME_1,
  MAN_ON_CROSSBAR_FRAME_3,
  MAN_ON_CROSSBAR_FRAME_2,
  MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_1,
  MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_3,
  MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_2,
  MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_1,
  MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_2,
  MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_3,
} from '../../data/sprites';

export const STAND_ANIMATION = { frames: [MAN_STANDING_FRAME_1, MAN_STANDING_FRAME_2], framesPerSecond: 2 };
export const MOVE_ANIMATION_LEFT = {
  frames: [MAN_MOVING_LEFT_FRAME_1, MAN_MOVING_LEFT_FRAME_2, MAN_MOVING_LEFT_FRAME_3, MAN_MOVING_LEFT_FRAME_2],
  framesPerSecond: 6,
};
export const MOVE_ANIMATION_RIGHT = {
  frames: [MAN_MOVING_RIGHT_FRAME_1, MAN_MOVING_RIGHT_FRAME_2, MAN_MOVING_RIGHT_FRAME_3, MAN_MOVING_RIGHT_FRAME_2],
  framesPerSecond: 6,
};
export const FALL_ANIMATION = {
  frames: [MAN_FALLING_FRAME_1, MAN_FALLING_FRAME_2, MAN_FALLING_FRAME_3, MAN_FALLING_FRAME_2],
  framesPerSecond: 10,
};
export const CLIMB_ANIMATION = {
  frames: [MAN_CLIMBING_FRAME_1, MAN_CLIMBING_FRAME_2, MAN_CLIMBING_FRAME_3, MAN_CLIMBING_FRAME_2],
  framesPerSecond: 10,
};
export const ON_STAIRS_ANIMATION = {
  frames: [MAN_ON_STAIRS_FRAME_1, MAN_ON_STAIRS_FRAME_2, MAN_ON_STAIRS_FRAME_3, MAN_ON_STAIRS_FRAME_2],
  framesPerSecond: 2,
};
export const ON_CROSSBAR_MOVE_LEFT_ANIMATION = {
  frames: [
    MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_1,
    MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_2,
    MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_3,
    MAN_ON_CROSSBAR_MOVE_LEFT_FRAME_2,
  ],
  framesPerSecond: 10,
};
export const ON_CROSSBAR_MOVE_RIGHT_ANIMATION = {
  frames: [
    MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_1,
    MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_2,
    MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_3,
    MAN_ON_CROSSBAR_MOVE_RIGHT_FRAME_2,
  ],
  framesPerSecond: 10,
};
export const ON_CROSSBAR_ANIMATION = {
  frames: [MAN_ON_CROSSBAR_FRAME_1, MAN_ON_CROSSBAR_FRAME_2, MAN_ON_CROSSBAR_FRAME_3, MAN_ON_CROSSBAR_FRAME_2],
  framesPerSecond: 2,
};


